### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by camaral** [brianhks/nexus-puppet-forge-plugin#4]
Hello, 
I would like to change your project but you didn't add a LICENSE. I forked it and I will add Apache 2.0 License, if you don't mind.
Let me know if you want it differently.
Cheers,
Caio

**Comment by brianhks** [comment]
Well crap.  Do a pull request and I'll suck it in.  I should have added that myself.

**Comment by camaral** [comment]
Done https://github.com/brianhks/nexus-puppet-forge-plugin/pull/5
Thank you very much!

**Comment by brianhks** [comment]
Thanks
